- name: varaibles from promt 
  hosts: local
  connection: local
  vars_prompt:
    - name: Name
      prompt: "Enter the User name"
      private: no    # we can use yes/no and true/false
    - name: Password
      prompt: "Enter the Password"
  tasks:
  - name: print the varaibles from promt
    ansible.builtin.debug:
      msg: "The User name is {{ Name }}" 