- name: vars in inventory
  hosts: web
  tasks:
  - name: print the variables from inventory.ini
    ansible.builtin.debug:
      msg: "The Course is {{ COURSE }} and the duration is {{ DURATION }}the Trainer is {{ TRAINER }}"