- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables
    GREET: "PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks: #task levelvariables
  - name: print the variable
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

#The order of precedence of variables in ansible is as follows:
  #1. Command line or args
  #2. Task level
  #3. Course.yaml Files
  #4. Prompt
  #5. Play 
  #6. Inventory
  #7. Roles
