- name: Condtions
  hosts: localhost
  connection: local
  vars:
    my_number: 10
  tasks:
  - name: print the number
    ansible.builtin.debug:
      msg: "The given {{ my_number }} is greater than 5"
    when: my_number > 5
  
  - name: print the number
    ansible.builtin.debug:
      msg: "The given {{ my_number }} is less than 5"
    when: my_number < 5