- name: loops 
  hosts: local
  connection: local
  tasks:
  - name: Printing the name
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
      - "John"
      - "Doe"
      - "Jane"
      - "Smith"