- name: filters
  hosts: local
  connection: local
  tasks:
  - name: Handle undefined variable
    ansible.builtin.debug:
      msg: "I am {{ name | default('John') }}"
  - name: convert from string to list 
    vars:
      fruits: "apple,banana,orange" # string
    ansible.builtin.debug:
      msg: "I like {{ fruits | split(',') }}"
  - name: convert from list to string
    vars:
      fruits: ["apple", "banana", "orange"] # list
    ansible.builtin.debug:
      msg: "I like {{ fruits | join(',') }}"
  - name: convert from  map to list
    vars:
      fruits:
        apple: 1
        banana: 2
    ansible.builtin.debug:
      msg: "I like {{ fruits | dict2items }}"
  - name: convert from list to map
    vars:
      fruits:
      - {'key': 'apple', 'value': 1}
      - {'key': 'banana', value: 2 }
    ansible.builtin.debug:
      msg: "I like {{ fruits | items2dict }}"
  - name: convert from list to dictionary
    vars:
      fruits:
      - {'key': 'apple', 'value': 1}
      - {'key': 'banana', value: 2 }
    ansible.builtin.debug:
      msg: "I like {{ fruits | items2dict }}"
  - name: convert to uppercase
    vars:
      name: "John"
    ansible.builtin.debug:
      msg: "I am {{ name | upper }}"
  - name: convert to lowercase
    vars:
      name: "John"
    ansible.builtin.debug:
      msg: "I am {{ name | lower }}"
  - name: convert to title case
    vars:
      name: "john doe"
    ansible.builtin.debug:
      msg: "I am {{ name | title }}"
  - name: convert to capitalize
    vars:
      name: "john doe"
    ansible.builtin.debug:
      msg: "I am {{ name | capitalize }}"
  - name: convert to reverse
    vars:
      name: "John"
    ansible.builtin.debug:
      msg: "I am {{ name | reverse }}"
  - name: convert to replace
    vars:
      name: "John"
    ansible.builtin.debug:
      msg: "I am {{ name | replace('John', 'Doe') }}" 
  - name: convert to slice
    vars:
      name: "John Doe"
    ansible.builtin.debug:
      msg: "I am {{ name | slice(0, 4) }}"
  - name: convert to trim
    vars:
      name: " John R. Doe "
    ansible.builtin.debug:
      msg: "I am {{ name | trim }}"
  