- name: filters
  hosts: local
  connection: local
  tasks:
  - name: Handle undefined variable
    ansible.builtin.debug:
      msg: "I am {{ name | default('John') }}"
  - name: convert from string to list 
    vars:
      fruits: "apple,banana,orange" # string
    ansible.builtin.debug:
      msg: "I like {{ fruits | split(',') }}"
  - name: convert from list to string
    vars:
      fruits: ["apple", "banana", "orange"] # list
    ansible.builtin.debug:
      msg: "I like {{ fruits | join(',') }}"