- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages in Node from server ec2-user
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"    #we can use present/installed  or absent/removed
    loop:
      - { name: 'php', state: 'absent' }
      - { name: 'vim', state: 'absent' }
      - { name: 'git', state: 'removed' }
      - { name: 'java', state: 'removed' }
      - { name: 'git', state: 'present' }
      - { name: 'php', state: 'present' }
      - { name: 'vim', state: 'installed' }
      - { name: 'java', state: 'installed' } 