- name: shell vs commands
  hosts: local
  connection: local
  tasks:
  - name: executing ls command module # It will work beacuse ls is present in command module if not present then it will not work
    ansible.builtin.command: ls
  - name: executing ls shell module
    ansible.builtin.shell: ls #-ltr > /tmp/output.txt