- name: Creating ec2 and route-53 records
  hosts: local
  connection: local
  vars:
    Subnet_Id: subnet-04c451dd811fac84b
    Securitygroup_Id: sg-021077680fed85f05
    AMI_Id: ami-09c813fb71547fc4f
    Instance_Type: t2.micro
    Instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install the packges
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: Create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ Subnet_Id }}"
      security_group: "{{ Securitygroup_Id }}"
      image_id: "{{ AMI_Id }}"
      instance_type: "{{ Instance_Type }}"
    loop: "{{ Instances }}"
    register: ec2_info

  - name: print ec2 info
    ansible.builtin.debug:
      msg : "{{ ec2-info }}"