- name: Creating ec2 and route-53 records
  hosts: local
  connection: local
  vars:
    Subnet_Id: subnet-04c451dd811fac84b
    Securitygroup_Id: sg-021077680fed85f05
    AMI_Id: ami-09c813fb71547fc4f
    Instance_Type: t2.micro
    Instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install the packges
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto2
    - botocore

