- name: install and run nginx
  hosts: web
  become: yes # -b for root access
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
      use: auto
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes