- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: Pirnt Hello Program
    ansible.builtin.debug:
      msg: "Hello Program"
