- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: Pirnt the variable
    ansible.builtin.debug:
      msg: "Course is DevOps with AWS, Duration of learing is 120hrs, Trainer is SelfLearnings"
  - name: print the variable
    vars: #task level variables
      COURSE: "Ansible"
      DURATION: 30HRS
      TRAINER: Sivakumar
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"


 
